workflows:
  react-native-eas-build:
    name: Expo EAS Build (Android & iOS)
    instance_type: mac_mini_m1
    max_build_duration: 60

    environment:
      vars:
        EXPO_TOKEN: $EXPO_TOKEN # Codemagic dashboardda qo‘shilgan
      flutter: stable
      xcode: latest

    scripts:
      - name: Install dependencies
        script: |
          npm install -g eas-cli
          npm install

      - name: Authenticate EAS
        script: |
          eas whoami

      - name: Build Android AAB
        script: |
          eas build --platform android --profile production --non-interactive

      - name: Build iOS IPA
        script: |
          eas build --platform ios --profile production --non-interactive

    artifacts:
      - ./android/app/build/outputs/**/*.aab
      - ./ios/build/**/*.ipa
