import { Dimensions, Platform, StyleSheet } from "react-native";

const { width, height: SCREEN_HEIGHT } = Dimensions.get("screen");

export const styles = StyleSheet.create({
  postContainer: {
    width: width,
    height: SCREEN_HEIGHT,
    backgroundColor: "#000",
  },
  media: {
    ...StyleSheet.absoluteFillObject,
  },
  // Simple background for gradient effect (React Native doesn't support CSS 'linear-gradient' natively)
  gradientTop: {
    position: "absolute",
    top: 0,
    width: "100%",
    height: 40,
    backgroundColor: "rgba(0,0,0,0.4)", // Simple dark overlay
  },
  gradientBottom: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    height: 230,
    backgroundColor: "rgba(0,0,0,0.5)", // Simple dark overlay
  },
  rightSidebar: {
    position: "absolute",
    right: 16,
    bottom: Platform.OS === "ios" ? 100 : 80,
    alignItems: "center",
    zIndex: 10,
  },
  avatarWrapper: {
    marginBottom: 30,
    position: "relative",
  },
  sidebarAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: 2,
    borderColor: "#fff",
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  followButton: {
    position: "absolute",
    bottom: -8,
    backgroundColor: "#ff3b5c",
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    borderWidth: 2,
    borderColor: "#000",
    shadowColor: "#ff3b5c",
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 3,
  },
  sidebarIconBtn: {
    alignItems: "center",
    marginBottom: 24,
    padding: 8,
  },
  sidebarIconText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "600",
    marginTop: 6,
    textShadowColor: "rgba(0,0,0,0.5)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  bottomContent: {
    position: "absolute",
    bottom: Platform.OS === "ios" ? 100 : 80,
    left: 16,
    right: 90,
    zIndex: 10,
  },
  userText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 8,
    textShadowColor: "rgba(0,0,0,0.4)",
    textShadowRadius: 2,
  },
  captionText: {
    color: "#fff",
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 12,
    textShadowColor: "rgba(0,0,0,0.3)",
    textShadowRadius: 2,
  },
  musicContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.12)",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    alignSelf: "flex-start",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 2,
  },
  musicText: {
    color: "#fff",
    fontSize: 13,
    marginLeft: 8,
    maxWidth: 220,
  },
  // Enhanced Comments Design
  commentHeader: {
    alignItems: "center",
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#333",
  },
  commentHeaderTitle: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
  },
  commentItem: {
    flexDirection: "row",
    marginTop: 20,
    alignItems: "flex-start",
    paddingBottom: 16,
    borderBottomWidth: 0.5,
    borderBottomColor: "#282828",
  },
  commentUserAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
    borderWidth: 1,
    borderColor: "#333",
  },
  commentTextContainer: {
    flex: 1,
  },
  commentUsername: {
    color: "#bbb",
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 4,
  },
  commentContent: {
    color: "#eee",
    fontSize: 15,
    lineHeight: 21,
  },
  commentFooter: {
    flexDirection: "row",
    marginTop: 8,
    alignItems: "center",
  },
  commentTime: {
    color: "#777",
    fontSize: 12,
    marginRight: 20,
  },
  replyText: {
    color: "#777",
    fontSize: 13,
    fontWeight: "600",
  },
  commentLikeContainer: {
    alignItems: "center",
    paddingLeft: 12,
    marginTop: 4,
  },
  commentLikeCount: {
    color: "#777",
    fontSize: 12,
    marginTop: 4,
  },
  // Replies Design
  repliesContainer: {
    marginTop: 10,
    paddingLeft: 10,
    borderLeftWidth: 1,
    borderLeftColor: "#444",
  },
  replyItem: {
    flexDirection: "row",
    marginTop: 10,
    alignItems: "flex-start",
  },
  replyAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    marginRight: 10,
  },
  replyTextContainer: {
    flex: 1,
  },
  replyUsername: {
    color: "#aaa",
    fontSize: 13,
    fontWeight: "600",
    marginBottom: 3,
  },
  replyContent: {
    color: "#ddd",
    fontSize: 14,
    lineHeight: 19,
  },
  replyTime: {
    color: "#666",
    fontSize: 11,
    marginTop: 4,
  },
  // Input Section Wrapper
  inputWrapper: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    backgroundColor: "#181818", // BottomSheet rangiga mos yoki biroz quyuqroq
    paddingTop: 8,
    paddingHorizontal: 16,
    paddingBottom: Platform.OS === "ios" ? 30 : 10,
    borderTopWidth: 1,
    borderTopColor: "#333",
    zIndex: 100, // BottomSheet ustida turishi uchun
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  smallAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    marginRight: 12,
  },
  textInput: {
    flex: 1,
    color: "#fff",
    fontSize: 15,
    maxHeight: 100,
    lineHeight: 20,
    backgroundColor: "#333",
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  sendBtn: {
    backgroundColor: "#ff3b5c",
    width: 38,
    height: 38,
    borderRadius: 19,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 12,
    shadowColor: "#ff3b5c",
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 3,
  },
});
