import { Dimensions, StyleSheet } from "react-native";
const { width, height } = Dimensions.get("window");
const COLUMN_WIDTH = (width - 40) / 2;
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#000" },
  header: { paddingTop: 60, paddingHorizontal: 20, paddingBottom: 20 },
  headerTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerTitle: { color: "#fff", fontSize: 32, fontWeight: "900" },
  headerSubtitle: { color: "#71717a", fontSize: 13, fontWeight: "600" },
  headerActions: { flexDirection: "row", gap: 10 },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "#18181b",
    alignItems: "center",
    justifyContent: "center",
  },
  badge: {
    position: "absolute",
    top: 12,
    right: 12,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#6366f1",
    borderWidth: 2,
    borderColor: "#18181b",
  },

  storiesContainer: { paddingVertical: 20 },
  storiesContent: { paddingHorizontal: 20, gap: 16 },
  storyWrap: { alignItems: "center" },
  storyContainer: { position: "relative" },
  avatarRing: {
    width: 76,
    height: 76,
    borderRadius: 24,
    padding: 3,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#18181b",
  },
  ringActive: {
    borderWidth: 3,
    borderColor: "#6366f1",
    backgroundColor: "transparent",
  },
  ringAdd: {
    borderWidth: 2,
    borderColor: "#3f3f46",
    borderStyle: "dashed",
  },
  storyImg: {
    width: "100%",
    height: "100%",
    borderRadius: 20,
  },
  liveBadge: {
    position: "absolute",
    bottom: -2,
    backgroundColor: "#ef4444",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#000",
  },
  liveText: {
    color: "#fff",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  addIconContainer: {
    position: "absolute",
    bottom: 0,
    right: 0,
    backgroundColor: "#18181b",
    borderRadius: 12,
    width: 24,
    height: 24,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#000",
  },
  storyName: {
    color: "#a1a1aa",
    fontSize: 12,
    marginTop: 8,
    fontWeight: "600",
    maxWidth: 76,
  },
  storyLoadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.75)",
    borderRadius: 24,
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  loadingText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "600",
    marginTop: 4,
  },

  catScroll: { paddingHorizontal: 20, marginBottom: 10, gap: 10 },
  catBtn: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: "#18181b",
  },
  catActive: { backgroundColor: "#fff" },
  catLabel: { color: "#71717a", fontWeight: "700", fontSize: 13 },
  catLabelActive: { color: "#000" },

  row: { justifyContent: "space-between", paddingHorizontal: 18 },
  snapCard: {
    width: COLUMN_WIDTH,
    height: COLUMN_WIDTH * 1.6,
    borderRadius: 30,
    overflow: "hidden",
    marginBottom: 18,
  },
  snapContent: {
    ...StyleSheet.absoluteFillObject,
    padding: 16,
    justifyContent: "space-between",
  },
  snapCategory: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(255,255,255,0.2)",
    padding: 5,
    borderRadius: 8,
    color: "#fff",
    fontSize: 10,
    fontWeight: "800",
  },
  snapUser: { color: "#fff", fontWeight: "800" },

  modalContainer: {
    flex: 1,
    backgroundColor: "#000",
  },
  storyImageContainer: {
    flex: 1,
  },
  fullStoryImage: {
    width: width,
    height: height,
    resizeMode: "cover",
  },
  storyOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  progressContainer: {
    position: "absolute",
    top: 54,
    left: 12,
    right: 12,
    flexDirection: "row",
    gap: 4,
  },
  progressBarBackground: {
    flex: 1,
    height: 2.5,
    backgroundColor: "rgba(255,255,255,0.25)",
    borderRadius: 2,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: "#fff",
    borderRadius: 2,
  },
  storyModalHeader: {
    position: "absolute",
    top: 70,
    left: 16,
    right: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  storyUserInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  storyAvatarSmall: {
    width: 42,
    height: 42,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: "#fff",
  },
  storyUserTitle: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 15,
  },
  storyTimestamp: {
    color: "#d4d4d8",
    fontSize: 12,
    marginTop: 2,
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "center",
    alignItems: "center",
  },
  storyFooter: {
    position: "absolute",
    bottom: 40,
    left: 16,
    right: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  replyInput: {
    flex: 1,
    height: 48,
    borderRadius: 24,
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.3)",
    backgroundColor: "rgba(0,0,0,0.3)",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 18,
    gap: 10,
  },
  replyPlaceholder: {
    color: "#999",
    fontSize: 14,
    fontWeight: "500",
  },
  actionButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(0,0,0,0.3)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.3)",
  },
});
